# Header
personal:
  figure: http://lh4.googleusercontent.com/-XEf0G3zWzjY/AAAAAAAAAAI/AAAAAAAAAAA/r2muasfnHgw/s96-c/photo.jpg
  slogan: less is MORE
  vcard: //kywi.github.io

# Left Menu
menu:
  Home:
    google: //google.com
    flickr: //flickr.com
    facebook: //facebook.com
  Insite:
    archive: /archive
    submenu1: /
    submenu2: /
    submenu3: /
  Dropdown1:
    submenu1: //
    submenu2: //
    submenu3: //
  Dropdown2:
    submenu1: //
    submenu2: //
    submenu3: //
    submenu4: //
    submenu5: //
links:
  google-plus: //google.com
  facebook: //facebook.com
  twitter: //
  vimeo2: //
  flickr: //
  linkedin: //
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
favicon: /favicon.png
google_analytics:
twitter:
google_plus:
